name: tech_haven
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  accordion: ^2.6.0
  animate_do: ^3.3.4
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.3
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.10
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.6
  currency_picker: ^2.0.21
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  firebase_storage: ^11.6.11
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  flutter_rating_stars: ^1.1.0
  flutter_slidable: ^3.1.0
  flutter_stripe: ^10.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_maps_flutter: ^2.6.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.1
  image_fade: ^0.6.2
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.3.0
  intl: 0.18.1
  like_button: ^2.0.5
  lottie: ^3.1.0
  path_provider: ^2.1.2
  pinput: ^4.0.0
  pull_to_refresh: ^2.0.0
  rive: ^0.13.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/lotties/welcome_page_lottie.json
    - assets/images/google-icon-logo-svgrepo-com.svg
    - assets/dev/hp-laptop-png.png
    - assets/dev/1619.jpg
    - assets/dev/ps5-png.png
    - assets/dev/iphone-png.png
    - assets/images/star-svgrepo-com.svg
    - assets/rive/animated_icon_set_.riv
    - assets/icons/arrow_right.svg
    - assets/icons/arrow_up.svg
    - assets/icons/camera.svg
    - assets/icons/cart.svg
    - assets/icons/cart_plus.svg
    - assets/icons/chevron_down.svg
    - assets/icons/dollar.svg
    - assets/icons/edit.svg
    - assets/icons/exclamation.svg
    - assets/icons/eye.svg
    - assets/icons/eye_slash.svg
    - assets/icons/globe.svg
    - assets/icons/heart.svg
    - assets/icons/map_pin.svg
    - assets/icons/map_pin_alt.svg
    - assets/icons/messages.svg
    - assets/icons/microphone.svg
    - assets/icons/play.svg
    - assets/icons/publish.svg
    - assets/icons/share.svg
    - assets/icons/star.svg
    - assets/icons/star_half.svg
    - assets/icons/thumb_up.svg
    - assets/icons/trash_bin.svg
    - assets/icons/user_add.svg
    - assets/icons/user_circle.svg
    - assets/icons/search.svg
    - assets/icons/settings.svg
    - assets/icons/settings_alt.svg
    - assets/icons/order_list.svg
    - assets/icons/angle_right.svg
    - assets/icons/outlined_star.svg
    - assets/icons/question_mark.svg
    - assets/icons/arrow_right_exit.svg
    - assets/icons/language.svg
    - assets/icons/translate.svg
    - assets/icons/angle_down.svg
    - assets/icons/arrow_left.svg
    - assets/icons/face_grin.svg
    - assets/logo/techHavenLogo.png
    - assets/logo/techHavenLogoHR.png
    - assets/icons/angle_up.svg
    - assets/icons/plus.svg
    - assets/icons/pen.svg
    - assets/icons/clock.svg
    - assets/icons/heart_filled.svg
    - assets/icons/upload.svg
    - assets/icons/close.svg

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/BeVietnamPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BeVietnamPro-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/BeVietnamPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BeVietnamPro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/BeVietnamPro-ThinItalic.ttf
          style: italic
          weight: 100
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
